Add ADR for Identity transactions
cheqd/cheqd-node pull request #119
Opened 2021-09-01 11:10 UTC by Toktar

2021-09-01 15:52 UTC, askolesov requested changes
Cool! Could you please add a state overview and queries?

2021-09-02 13:17 UTC, Toktar commented
@askolesov Added state formats

2021-09-02 13:18 UTC, Toktar commented
@esplinr Could you please review this.

2021-09-09 00:03 UTC, ankurdotb approved these changes

2021-09-09 00:11 UTC, ankurdotb approved these changes

2021-09-09 00:16 UTC, merged