Bump IBC, Cosmos-SDK, Tendermint to latest versions
cheqd/cheqd-node pull request #183
Opened 2021-11-05 23:14 UTC by faddat

Since IBC v1.0.2, there have been multiple security rleases of IBC-Go.  This bumps that to 1.2.2 and bumps Tendermint and the Cosmos SDK to 0.34.14 and 0.44.3, respectively.  Together, these will make for a more performant node, especially from the perspective of a relayer.﻿

2021-11-08 11:16 UTC, askolesov approved these changes

2021-11-08 11:17 UTC, askolesov commented
Thanks! @ankurdotb Are you OK with merging this?

2021-11-08 11:25 UTC, ankurdotb requested changes
@Toktar @askolesov @anikitinDSR Also cross-check the dependencies for go.mod, remove any unnecessary and if there's any other versions bumped to higher upstream, change those as well.

2021-11-08 11:25 UTC, ankurdotb commented on go.mod
> +	nhooyr.io/websocket v1.8.6 // indirect
This library is the one that is dependent on vulnerable version of `gin-gonic` but doesn't seem to be used any more in Cosmos SDK or Tendermint upstream.

Cosmos fix in v0.44.3: https://github.com/cosmos/cosmos-sdk/blob/b75c29fc15d3320ec0c7596dbd7c787c48dccad8/go.mod#L67

Tendermint also doesn't use it.

2021-11-09 18:15 UTC, ankurdotb commented
This might be superseded by https://github.com/cheqd/cheqd-node/pull/186 if everything is incorporporated there.

2021-11-09 20:11 UTC, ankurdotb commented
@faddat The go version suggested is also higher than that used by Cosmos SDK.

2021-11-10 11:35 UTC, ankurdotb commented
Resolved under https://github.com/cheqd/cheqd-node/pull/186 and superseded

2021-11-10 11:35 UTC, closed without merging