[DEV-1171] Add additional instruction for updating from 0.4.x version
cheqd/cheqd-node pull request #301
Opened 2022-03-21 16:56 UTC by anikitinDSR

Signed-off-by: Andrew Nikitin <andrew.nikitin@cheqd.io>

2022-03-21 16:57 UTC, ankurdotb commented
Task linked: [DEV-1171 Change update instructions for `0.5.0` release.](https://app.clickup.com/t/6600954/DEV-1171)

2022-03-22 11:28 UTC, Toktar requested changes
I suggest adding a section for this information and extend it, like for "Upgrade from 0.2.x". Keep this warning but add a link to a new section.

2022-03-22 11:58 UTC, Toktar approved these changes
Nice work! Thanks

2022-03-22 12:03 UTC, Toktar approved these changes

2022-03-22 12:03 UTC, merged