tx.proto commit
cheqd/cheqd-node pull request #332
Opened 2022-06-17 19:21 UTC by khornonzon

2022-06-17 19:35 UTC, Toktar requested changes
Could you please start with a Plan of Attack?

2022-06-17 19:35 UTC, Toktar commented on proto/cheqd/v1/tx.proto
> +  string id = 2;
Why this proto doesn't contain only `id` field?

2022-06-17 19:35 UTC, Toktar commented on proto/cheqd/v1/tx.proto
> +  string id = 1;
Let's add a metadata and maybe a full DidDoc to a response

2022-06-28 13:27 UTC, Toktar commented on scripts/protocgen.sh
> +#    protoc \
Could you please return these lines?

2022-06-28 13:28 UTC, Toktar commented on scripts/protocgen.sh
> -  buf protoc \
Could you please return this?

2022-06-28 13:29 UTC, Toktar commented on x/cheqd/types/query.pb.gw.go
> +	pattern_Query_Did_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 1, 0, 4, 1, 5, 3}, []string{"cheqd", "v1", "did", "id"}, "", runtime.AssumeColonVerbOpt(true)))
Could you please return this?

2022-07-05 12:05 UTC, Toktar commented on x/cheqd/client/cli/tx_deactivate_did.go
> +		Use:   "deactivate-did [payload-json] [ver-method-id-1] [priv-key-1] [ver-method-id-N] [priv-key-N] ...",
Why `payload-json`? It may be just "id"

2022-07-05 12:14 UTC, Toktar commented on x/cheqd/keeper/msg_server_deactivate_did.go
> +	signers := GetSignerDIDsForDIDDeactivation(*existingDid, *updatedDid)
Why does this method use 2 params. Only existingDid is needed. `GetSignerDIDsForDIDDeactivation` should look like  `GetSignerDIDsForDIDCreation`

2022-07-05 12:19 UTC, Toktar commented on x/cheqd/keeper/msg_server_deactivate_did.go
> +	}
```suggestion
	err = VerifyAllSignersHaveAllValidSignatures(&k.Keeper, &ctx, inMemoryDids, msg.Payload.GetSignBytes(), signers, msg.Signatures)
	if err != nil {
		return nil, err
	}

	// Build state value
	value, err := types.NewStateValue(&existingDid, &updatedMetadata)
	if err != nil {
		return nil, err
	}

	err = k.SetDid(&ctx, &value)
	if err != nil {
		return nil, types.ErrInternal.Wrapf(err.Error())
	}
```
The better way

2022-07-05 12:21 UTC, Toktar commented on x/cheqd/keeper/msg_server_deactivate_did.go
> +	res = append(res, updatedDid.GetVerificationMethodControllers()...)
```suggestion
func GetSignerDIDsForDIDDeactivation(did types.Did) []string { 
        res := did.GetControllersOrSubject()
	res = append(res, did.GetVerificationMethodControllers()...)
```

2022-07-05 12:25 UTC, Toktar commented on x/cheqd/tests/deactivate_did_test.go
> +	}
```suggestion
keys := GenerateTestKeys()
```

2022-07-05 12:27 UTC, Toktar commented on x/cheqd/tests/deactivate_did_test.go
> +			name:  "Valid: Key rotation works",
Key rotation is impossible for Deactivation tx. Changing the test name is needed

2022-07-05 12:28 UTC, Toktar commented on x/cheqd/tests/deactivate_did_test.go
> +	cases := []struct {
Could you add negative tests too?

2022-07-05 12:46 UTC, Toktar commented on x/cheqd/types/tx_msg_deactivate_did_payload.go
> +	return msg.ToDid().Validate(allowedNamespaces)
```suggestion
	return validation.ValidateStruct(&msg,
		validation.Field(&msg.Id, validation.Required, IsDID(allowedNamespaces)),
	        )
```
+ add `validation "github.com/go-ozzo/ozzo-validation/v4"` to `import`
+ remove `ToDid` method

2022-09-06 03:04 UTC, Tweeddalex commented
Hey @Toktar it would be good to understand what the status is here. Is the deactivate DID feature complete now? What are the next steps?

2022-09-29 08:48 UTC, askolesov approved these changes
Looks great! Thanks.

2022-09-29 08:49 UTC, askolesov commented
Does anybody know why my commits don't trigger pipelines?

2022-09-29 08:50 UTC, askolesov commented
Ok, got it, because it's a fork. We need a way to trigger them befor merge.

2022-09-29 08:52 UTC, askolesov requested changes
We need to trigger pipelines

2022-09-30 15:57 UTC, Toktar approved these changes

2022-10-17 08:21 UTC, ankurdotb commented
Task linked: [DEV-1774 Merge DID Deactivation PRs](https://app.clickup.com/t/6600954/DEV-1774)

2022-10-26 09:12 UTC, askolesov approved these changes

2022-10-26 09:13 UTC, merged