fix: v1 hotfix
cheqd/cheqd-node pull request #474
Opened 2022-12-12 14:06 UTC by Eengineer1

- Fixes ICA module store key initialisation.

2022-12-13 12:01 UTC, ankurdotb requested changes
1. Send exact details of what was migrated _if_ the node's logging mode is set to debug mode. This should include previous data _and_ new data. Skip Protobuf migrations and do it for everything else.
2. Query the module version map at v0.6.9 **before** upgrade as well (no need for earlier upgrade sequences). This should match what is currently on mainnet before trying to upgrade to v1.0.x

2022-12-13 15:08 UTC, Eengineer1 commented on app/const.go
>  	UpgradeName = "v1.0.0"
Added.

2022-12-13 15:22 UTC, ankurdotb commented
Task linked: [DEV-1973 Fix upgrade handler for v1.0.0 migrations](https://app.clickup.com/t/6600954/DEV-1973)

2022-12-13 18:37 UTC, ankurdotb requested changes
LGTM!

2022-12-13 19:15 UTC, ankurdotb reviewed
There are a lot of comments in here for InterChain accounts which I'm not 100% sure whether necessary. Also, added a review comment on one specific bit regarding keepers.

2022-12-13 19:15 UTC, ankurdotb commented on app/app.go
>  		icaModule,
Does this one not need an `app.<x>Keeper` call?

2022-12-14 11:09 UTC, ankurdotb approved these changes

2022-12-14 11:09 UTC, merged