fix: Debug logging for migration handlers [DEV-1974]
cheqd/cheqd-node pull request #478
Opened 2022-12-13 14:55 UTC by abdulla-ashurov

- Add migration logs for DID and resources

2022-12-13 14:55 UTC, ankurdotb commented
Task linked: [DEV-1974 Log migrations for DIDs and resources if in debug mode](https://app.clickup.com/t/6600954/DEV-1974)

2022-12-13 16:27 UTC, ankurdotb requested changes
Log all changes that happen, not just Indy-style to new-style version migrations

2022-12-13 19:22 UTC, ankurdotb commented
@abdulla-ashurov I've retargetted this to main

2022-12-13 19:25 UTC, abdulla-ashurov commented
> @abdulla-ashurov I've retargetted this to main

@ankurdotb Thanks 🙏

2022-12-14 08:53 UTC, abdulla-ashurov commented
> Log all changes that happen, not just Indy-style to new-style version migrations

@ankurdotb Done! ✅

2022-12-14 14:43 UTC, ankurdotb requested changes
1. **Protobufs**
    1. migrations.MigrateDidProtobuf: Old and new metadata
    2. migrations.MigrateResourceProtobuf: Nothing
2. **Indy style**
    1. `migrations.MigrateDidIndyStyle`: Old DID and new DID (not DIDDoc, just ID)  
    2. `migrations.MigrateResourceIndyStyle: Old and new Collection ID
4. **UUID normalization**
    1. migrations.MigrateDidUUID: Old DID and new DID (not DIDDoc, just ID)  
    2. migrations.MigrateResourceUUID: Old and new Collection ID
5. `migrations.MigrateDidVersionId`: DID ID, old version, new version
6. `migrations.MigrateResourceChecksum`: Collection ID, Resource ID, old and new checksum
7. `migrations.MigrateResourceVersionLinks`: Collection ID, Resource, old and new version links
8. `migrations.MigrateResourceDefaultAlternativeUrl`: Collection ID, Resource ID, Alternative URL

2022-12-14 17:30 UTC, abdulla-ashurov commented on app/app.go
> +
Done! ✅

2022-12-15 10:49 UTC, ankurdotb approved these changes

2022-12-15 10:49 UTC, merged